# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, baseUnicodeSymbols, basicPrelude, cpphs, foldl
, systemFilepath, text, turtle
}:

cabal.mkDerivation (self: {
  pname = "preprocess-haskell";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    baseUnicodeSymbols basicPrelude cpphs foldl systemFilepath text
    turtle
  ];
  meta = {
    description = "Preprocess Haskell Repositories";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
